### ISSUE TITLE
How to set screen size?

### ISSUE THREAD

**Issue by jbrepogmailcom** [takeyamayuki/NonMouse#16]
Hello the mouse only works on left two thirds of the screen. I gues it has something to do with screen size, my lapto has 1920x1080. Can I reconfigure it somewhere?

**Comment by takeyamayuki** [comment]
Hi, sorry for the late reply.
Thank you for setting up the issue.

Perhaps it is due to this part.
https://github.com/takeyamayuki/NonMouse/blob/c80fe96b51c20e6b39e463a8ca4861c56e62972a/app.py#L30-L31

I suspect it is a bug in tkinter, please try changing your tkinter version to the latest one.
