### ISSUE TITLE
ZeroDivisionErrorでクラッシュする

### ISSUE THREAD

**Issue by takpika** [takeyamayuki/NonMouse#9]
`cfps = int(cap.get(cv2.CAP_PROP_FPS))`
でcfpsが1になって
`
if cfps < 30:
        cap.set(cv2.CAP_PROP_FRAME_WIDTH, cap_width)
        cap.set(cv2.CAP_PROP_FRAME_HEIGHT, cap_height)
        cfps = int(cap.get(cv2.CAP_PROP_FPS))
`
を通してもcfpsが1になり、
`ran = int(cfps/10)`
でranが0になってしまい、ZeroDivisionErrorでクラッシュします。

環境は以下の通りです
PC: MacBook Pro 2020 Intel
OS: macOS Monterey
カメラ: Mac内蔵Webカメラ
Pythonバージョン: 3.9.7

**Comment by takeyamayuki** [comment]
タイトルに「macOS Montereyにおいて」を追加します。
